// This file is automatically generated by qtc from "history.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line history.qtpl:1
package templates

//line history.qtpl:1
import (
	"isubata/types"
)

//line history.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line history.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line history.qtpl:7
type HistoryView struct {
	ChannelID int64
	Channels  []types.ChannelInfo
	Messages  []types.MessageWithUser
	MaxPage   int64
	Page      int64
	User      types.User
}

//line history.qtpl:18
func (h HistoryView) StreamHTML(qw422016 *qt422016.Writer) {
	//line history.qtpl:18
	qw422016.N().S(`

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html" charset="utf-8">
    <title>Isubata</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/main.css">
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/tether.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
  </head>
  <body>

  <nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right hidden-lg-up" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Isubata</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="nav navbar-nav ml-auto">
        <li class="nav-item"><a href="/history/`)
	//line history.qtpl:41
	qw422016.E().V(h.ChannelID)
	//line history.qtpl:41
	qw422016.N().S(`" class="nav-link">チャットログ</a></li>
        <li class="nav-item"><a href="/add_channel" class="nav-link">チャンネル追加</a></li>
        <li class="nav-item"><a href="/profile/`)
	//line history.qtpl:43
	qw422016.N().Q(h.User.Name)
	//line history.qtpl:43
	qw422016.N().S(`" class="nav-link">`)
	//line history.qtpl:43
	qw422016.N().Q(h.User.DisplayName)
	//line history.qtpl:43
	qw422016.N().S(`</a></li>
        <li class="nav-item"><a href="/logout" class="nav-link">ログアウト</a></li>
        <li><a href="/register" class="nav-link">新規登録</a></li>
        <li><a href="/login" class="nav-link">ログイン</a></li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid">
  <div class="row">
    <nav class="col-sm-3 col-md-3 hidden-xs-down bg-faded sidebar">
      <ul class="nav nav-pills flex-column">
        `)
	//line history.qtpl:55
	for _, ch := range h.Channels {
		//line history.qtpl:55
		qw422016.N().S(`
          <li class="nav-item">
            <a class="nav-link justify-content-between `)
		//line history.qtpl:57
		if h.ChannelID == ch.ID {
			//line history.qtpl:57
			qw422016.N().S(` active `)
			//line history.qtpl:57
		}
		//line history.qtpl:57
		qw422016.N().S(`"
               href="/channel/`)
		//line history.qtpl:58
		qw422016.E().V(ch.ID)
		//line history.qtpl:58
		qw422016.N().S(`">
                `)
		//line history.qtpl:59
		qw422016.N().Q(ch.Name)
		//line history.qtpl:59
		qw422016.N().S(`
              <span class="badge badge-pill badge-primary float-right" id="unread-`)
		//line history.qtpl:60
		qw422016.E().V(ch.ID)
		//line history.qtpl:60
		qw422016.N().S(`"></span>
            </a>
          </li>
        `)
		//line history.qtpl:63
	}
	//line history.qtpl:63
	qw422016.N().S(`
      </ul>
    </nav>
    <main class="col-sm-9 offset-sm-3 col-md-9 offset-md-3 pt-3">

      <div id="history">
        `)
	//line history.qtpl:69
	for _, msg := range h.Messages {
		//line history.qtpl:69
		qw422016.N().S(`
          <div class="media message">
            <img class="avatar d-flex align-self-start mr-3" src="/icons/`)
		//line history.qtpl:71
		qw422016.N().Q(msg.UserAvatarIcon)
		//line history.qtpl:71
		qw422016.N().S(`" alt="no avatar">
            <div class="media-body">
              <h5 class="mt-0"><a href="/profile/`)
		//line history.qtpl:73
		qw422016.N().Q(msg.UserName)
		//line history.qtpl:73
		qw422016.N().S(`">`)
		//line history.qtpl:73
		qw422016.N().Q(msg.UserDisplayName)
		//line history.qtpl:73
		qw422016.N().S(`@`)
		//line history.qtpl:73
		qw422016.N().Q(msg.UserName)
		//line history.qtpl:73
		qw422016.N().S(`</a></h5>
              <p class="content">`)
		//line history.qtpl:74
		qw422016.N().Q(msg.MessageContent)
		//line history.qtpl:74
		qw422016.N().S(`</p>
              <p class="message-date">`)
		//line history.qtpl:75
		qw422016.E().V(msg.MessageCreatedAt.Format("2006/01/02 15:04:05"))
		//line history.qtpl:75
		qw422016.N().S(`</p>
            </div>
          </div>
        `)
		//line history.qtpl:78
	}
	//line history.qtpl:78
	qw422016.N().S(`
      </div>

      <nav>
        <ul class="pagination">
          `)
	//line history.qtpl:83
	if h.Page != 1 {
		//line history.qtpl:83
		qw422016.N().S(`
            <li><a href="/history/`)
		//line history.qtpl:84
		qw422016.E().V(h.ChannelID)
		//line history.qtpl:84
		qw422016.N().S(`?page=`)
		//line history.qtpl:84
		qw422016.E().V((h.Page - 1))
		//line history.qtpl:84
		qw422016.N().S(`"><span>«</span></a></li>
          `)
		//line history.qtpl:85
	}
	//line history.qtpl:85
	qw422016.N().S(`

          `)
	//line history.qtpl:87
	for p := int64(1); p <= h.MaxPage; p++ {
		//line history.qtpl:87
		qw422016.N().S(`
            `)
		//line history.qtpl:88
		if p == h.Page {
			//line history.qtpl:88
			qw422016.N().S(`
              <li class="active">
            `)
			//line history.qtpl:90
		} else {
			//line history.qtpl:90
			qw422016.N().S(`
              <li>
            `)
			//line history.qtpl:92
		}
		//line history.qtpl:92
		qw422016.N().S(`
                <a href="/history/`)
		//line history.qtpl:93
		qw422016.E().V(h.ChannelID)
		//line history.qtpl:93
		qw422016.N().S(`?page=`)
		//line history.qtpl:93
		qw422016.E().V(p)
		//line history.qtpl:93
		qw422016.N().S(`">
                  `)
		//line history.qtpl:94
		qw422016.E().V(p)
		//line history.qtpl:94
		qw422016.N().S(`
                </a>
              </li>
          `)
		//line history.qtpl:97
	}
	//line history.qtpl:97
	qw422016.N().S(`

          `)
	//line history.qtpl:99
	if h.Page != h.MaxPage {
		//line history.qtpl:99
		qw422016.N().S(`
            <li><a href="/history/`)
		//line history.qtpl:100
		qw422016.E().V(h.ChannelID)
		//line history.qtpl:100
		qw422016.N().S(`?page=`)
		//line history.qtpl:100
		qw422016.E().V((h.Page + 1))
		//line history.qtpl:100
		qw422016.N().S(`"><span>»</span></a></li>
          `)
		//line history.qtpl:101
	}
	//line history.qtpl:101
	qw422016.N().S(`
        </ul>
      </nav>

    </main>
</div></div></body></html>
`)
//line history.qtpl:107
}

//line history.qtpl:107
func (h HistoryView) WriteHTML(qq422016 qtio422016.Writer) {
	//line history.qtpl:107
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line history.qtpl:107
	h.StreamHTML(qw422016)
	//line history.qtpl:107
	qt422016.ReleaseWriter(qw422016)
//line history.qtpl:107
}

//line history.qtpl:107
func (h HistoryView) HTML() string {
	//line history.qtpl:107
	qb422016 := qt422016.AcquireByteBuffer()
	//line history.qtpl:107
	h.WriteHTML(qb422016)
	//line history.qtpl:107
	qs422016 := string(qb422016.B)
	//line history.qtpl:107
	qt422016.ReleaseByteBuffer(qb422016)
	//line history.qtpl:107
	return qs422016
//line history.qtpl:107
}
