// This file is automatically generated by qtc from "messages.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line messages.qtpl:1
package templates

//line messages.qtpl:1
import "time"

//line messages.qtpl:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line messages.qtpl:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line messages.qtpl:5
type MessageWithUser struct {
	UserName        string `db:"name"`
	UserDisplayName string `db:"display_name"`
	UserAvatarIcon  string `db:"avatar_icon"`

	MessageID        int64     `db:"msg_id"`
	MessageContent   string    `db:"content"`
	MessageCreatedAt time.Time `db:"created_at"`
}

type MessageMarshaler struct {
	Msgs []MessageWithUser
}

//line messages.qtpl:21
func (mm *MessageMarshaler) StreamJSON(qw422016 *qt422016.Writer) {
	//line messages.qtpl:21
	qw422016.N().S(`[`)
	//line messages.qtpl:23
	for i, msg := range mm.Msgs {
		//line messages.qtpl:23
		qw422016.N().S(`{"content":`)
		//line messages.qtpl:25
		qw422016.E().Q(msg.MessageContent)
		//line messages.qtpl:25
		qw422016.N().S(`,"date":`)
		//line messages.qtpl:26
		qw422016.E().Q(msg.MessageCreatedAt.Format("2006/01/02 15:04:05"))
		//line messages.qtpl:26
		qw422016.N().S(`,"id":`)
		//line messages.qtpl:27
		qw422016.E().V(msg.MessageID)
		//line messages.qtpl:27
		qw422016.N().S(`,"user": {"name":`)
		//line messages.qtpl:29
		qw422016.E().Q(msg.UserName)
		//line messages.qtpl:29
		qw422016.N().S(`,"display_name":`)
		//line messages.qtpl:30
		qw422016.E().Q(msg.UserDisplayName)
		//line messages.qtpl:30
		qw422016.N().S(`,"avatar_icon":`)
		//line messages.qtpl:31
		qw422016.E().Q(msg.UserAvatarIcon)
		//line messages.qtpl:31
		qw422016.N().S(`}}`)
		//line messages.qtpl:34
		if i+1 < len(mm.Msgs) {
			//line messages.qtpl:34
			qw422016.N().S(`,`)
			//line messages.qtpl:34
		}
		//line messages.qtpl:35
	}
	//line messages.qtpl:35
	qw422016.N().S(`]`)
//line messages.qtpl:37
}

//line messages.qtpl:37
func (mm *MessageMarshaler) WriteJSON(qq422016 qtio422016.Writer) {
	//line messages.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line messages.qtpl:37
	mm.StreamJSON(qw422016)
	//line messages.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line messages.qtpl:37
}

//line messages.qtpl:37
func (mm *MessageMarshaler) JSON() string {
	//line messages.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
	//line messages.qtpl:37
	mm.WriteJSON(qb422016)
	//line messages.qtpl:37
	qs422016 := string(qb422016.B)
	//line messages.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
	//line messages.qtpl:37
	return qs422016
//line messages.qtpl:37
}
